version: '3.4'

services:
  addressbook.db:
    container_name: sqldb
    environment:
      MSSQL_SA_PASSWORD: Password123
      ACCEPT_EULA: "Y"

    restart: always
    ports:
      - "1433:1433"
    
  addressbook.api:
    container_name: addressbook.api
    environment:
      - "ConnectionStrings:AddressBookConnectionString=Server=sqldb;Database=AddressBookDb;User Id=sa;Password=Password123;Encrypt=False;"
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "7001:80"
    depends_on:
      - addressbook.db
