version: '3.4'

services:
  addressbook.db:
    image: mcr.microsoft.com/mssql/server:2019-CU14-ubuntu-20.04

  addressbook.api:
    image: ${DOCKER_REGISTRY-}addressbook
    build:
      context: .
      dockerfile: AddressBook.API/Dockerfile